[package]
edition.workspace = true
name = "documented-test"
publish = false
rust-version.workspace = true
version.workspace = true

[dependencies]
documented.workspace = true

[features]
customise = ["documented/customise"]
default = ["customise"]
