# This workflow is manually triggered.

name: publish-crate
on:
  workflow_dispatch:

jobs:
  publish-to-crates-io:
    name: Publish to crates.io
    runs-on: ubuntu-latest

    environment: crates.io-publish
    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Obtain OIDC token
        uses: rust-lang/crates-io-auth-action@v1
        id: auth

      - name: Run cargo publish
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ steps.auth.outputs.token }}
